navikt/pensjonsbrev

- pensjon-brevbaker/build.gradle.kts
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/api/Utils.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/UfoerOmregningEnslig.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/TestFrase.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/UfoerOmregningEnslig.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/VedleggOrienteringOmRettigheter.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/EgenerklaeringPleieOgOmsorgsarbeid.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/OrienteringOmRettigheter.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/IncludeAttachment.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/Language.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/LetterTemplate.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/Phrase.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/base/PensjonLatex.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/dsl/Template.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/dsl/Utils.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/LanguageTest.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/dsl/TemplateTest.kt
Nå kan vi bruke fraser, vedlegg osv. som har støtte for flere språk enn hva malene har.
> Endre språktyper slik at man kan bruke en frase med støtte for flere språk

- pensjon-brevbaker-api-model/build.gradle.kts
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/Felles.kt
Vi bruker ikke feltet lenger. Det er nå lagret i Adresse.linje1.
> Gjør Navn.kortnavn optional, og marker det som deprecated

- pdf-bygger/src/main/kotlin/no/nav/pensjon/brev/pdfbygger/Application.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/Application.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/Utils.kt
Svar med 400 - bad request og en beskrivelse av hva som feilet.
Endre logging i pdf-bygger også.
> Endre til 400 svar ved feilet json deserialisering

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/latex/LaTeXCompilerService.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/latex/LatexPrintWriter.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/EksempelBrev.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/LetterTemplate.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/Operations.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/Utils.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/base/PensjonLatex.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/dsl/Template.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/dsl/TemplateTable.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/dsl/expression/Date.kt
- pensjon-brevbaker/src/main/resources/latex/content.tex
- pensjon-brevbaker/src/main/resources/latex/firstpage.tex
- pensjon-brevbaker/src/main/resources/latex/pensjonsbrev_v3.cls
- pensjon-brevbaker/src/main/resources/latex/tabularray.sty
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/dsl/TemplateTableTest.kt
Add multi row column header support.
Adjust firstpage footer spacing.
Manually use latest version of tabularray(not in any repository except github). Needed to fix intermittent formatting bugs related to setting \parskip.
Remove table color selection support as it is now taken care of with table styling.
Fix formatting issues when a multicolumn row expands over all columns.
Remove unused floatbarrier as it longtblr is not a float.
> PL-5083: Multi page table bugfixes and styling.

- pensjon-brevbaker-api-model/build.gradle.kts
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/vedlegg/MaanedligUfoeretrygdFoerSkatt.kt
Legger til ektefelletillegg, gjenlevendetillegg og barnetillegg felles barn i VedleggMaanedligeUfoeretrgdFoerSkatt.
> Legger til felter i VedleggMaanedligeUfoeretrgdFoerSkatt steg 1

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/UngUfoerAuto.kt
Legger til kriterier på inkludering av vedlegg månedlig uføretrygd før skatt i ung ufør auto.
> PL-6149: Legger til kriterier på inkludering av vedlegg 

- pensjon-brevbaker-api-model/build.gradle.kts
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/vedlegg/MaanedligUfoeretrygdFoerSkatt.kt
PL-6176 part 1: forberedelse til fjerning og renaming av felter.
> PL-6176 part 1: forberedelse til fjerning og renaming av felter.

- pensjon-brevbaker-api-model/build.gradle.kts
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/OpphoerBarnetilleggAuto.kt
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/vedlegg/OpplysningerBruktIBeregning.kt
ny api-modell versjon i forberedelse for retting i opplysninger om barnetillegg.
> PL-5105: ny api-modell

- .github/CODEOWNERS
Setter opp CODEOWNERS for etterlatte så de ikke trenger approoval fra oss innenfor /etterlatte
> Setter opp CODEOWNERS for etterlatte.

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/EtterlatteBrevRequest.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/TemplateResource.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/OMSInnvilgelse.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/common/Constants.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/common/OMSFelles.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/OMSInnvilgelseAuto.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/OMSInnvilgelseManuell.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/Fixtures.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OMSInnvilgelseDTO.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/maler/OMSInnvilgelseAutoTest.kt
Oppretter mal for OMS innvilgelse og flytter felles OMS fraser til eget objekt
> Opprett mal for oms innvilgelse

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/OMSInnvilgelseAuto.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelseDTO.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OMSInnvilgelseDTO.kt
Endring for å ta i bruk nyeste info om avkorting
> Bruk kun avkortingsinfo i oms

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/EtterlatteBrevRequest.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/TemplateResource.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/common/Constants.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/common/OMSFelles.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/OMSOpphoerManuell.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/KlageOgAnke.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/maler/OMSOpphoerManuellTest.kt
> Lag manuelt brev for manuelt opphoer oms

- pensjon-brevbaker-api-model/build.gradle.kts
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/OpphoerBarnetilleggAuto.kt
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/vedlegg/OrienteringOmRettigheterUfoere.kt
PL-5105: Api model for å kunne differensiere mellom innvilget barnetillegg felles barn og særkulllsbarn.
> PL-5105: Api model for å kunne differensiere mellom innvilget barnetillegg felles barn og særkulllsbarn.

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/ForhaandsvarselEtteroppgjoerUfoeretrygdAuto.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/ufoer/Etteroppgjoer.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/VedleggOpplysningerOmEtteroppgjoeret.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/VedleggOrienteringOmRettigheter.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/DineRettigheterOgPlikterUfoere.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/OpplysningerOmEtteroppgjoeret.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/PraktiskInformasjonEtteroppgjoerUfoeretrygd.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/maler/ForhaandsvarselEtteroppgjoerUfoeretrygdAutoTest.kt
Diverse text changes and corrections
> Diverse text changes and corrections

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocGjenlevenderettFoed1954Til1957.kt
> Rettet nynorsk tekst 

- skribenten-backend/.nais/dev.yaml
- skribenten-backend/.nais/nais.yaml
- skribenten-frontend/.nais/nais.yaml
Ref documentasjonen må man eksplisitt tillate at brukere kan få tilgang via obo-tokens: https://doc.nais.io/security/auth/azure-ad/configuration/#users
> Add allow all users and trygdeetaten for dev

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/ny/BarnepensjonInnvilgelseEnkel.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/ny/BarnepensjonInnvilgelseNy.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonInnvilgelseFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/innvilgelse/BarnepensjonInnvilgelseEnkelFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/common/Constants.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/common/Felles.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/Trygdetidstabell.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/BeregningAvBarnepensjon.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/Beregningsperiodetabell.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/DineRettigheterOgPlikterBP.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/EtterbetalingAvBarnepensjon.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/InformasjonTilDegSomHandlerPaaVegneAvBarnet.kt
Inkludert vedlegg
Basert på https://confluence.adeo.no/display/TE/Brevmaler+-+Gammelt+regelverk+%28GBP%29+Barnepensjon
> Sett om innvilgelsesbrevet til nynorsk og engelsk

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverk.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/ForhaandsvarselOmregningBP.kt
> Omsetjing av førehandsvarsel til engelsk

- gradle.properties
- pensjon-brevbaker-api-model/build.gradle.kts
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/UfoerOmregningEnslig.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/UfoerOmregningEnslig.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/UfoerOmregningEnslig.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/opplysningerbruktiberegningufoere/OpplysningerOmMinstetillegg.kt
NAV-11803: Små fiks i innhold UfoerOmregningEnslig. Gjør vedlegget optional
> NAV-11803: Små fiks i innhold UfoerOmregningEnslig. Gjør vedlegget optional

- build.gradle.kts
bugfix. Inkluderer api-model-common for henting av artifakt fra maven pkg.github.com.
> bugfix. Inkluderer api-model-common for henting av artifakt

- skribenten-backend/fetch-secrets.sh
- tjenestebuss-integrasjon/.nais/azure-ad-app-lokal.yml
- tjenestebuss-integrasjon/.nais/dev-q2.yaml
- tjenestebuss-integrasjon/.nais/dev.yaml
- tjenestebuss-integrasjon/.nais/nais.yaml
- tjenestebuss-integrasjon/build.gradle.kts
- tjenestebuss-integrasjon/fetch-secrets.sh
- tjenestebuss-integrasjon/src/main/kotlin/no/nav/pensjon/brev/tjenestebuss/tjenestebussintegrasjon/Metrics.kt
- tjenestebuss-integrasjon/src/main/kotlin/no/nav/pensjon/brev/tjenestebuss/tjenestebussintegrasjon/Routing.kt
- tjenestebuss-integrasjon/src/main/kotlin/no/nav/pensjon/brev/tjenestebuss/tjenestebussintegrasjon/TjenestebussIntegrasjonApplication.kt
- tjenestebuss-integrasjon/src/main/kotlin/no/nav/pensjon/brev/tjenestebuss/tjenestebussintegrasjon/auth/Authorization.kt
- tjenestebuss-integrasjon/src/main/resources/application.conf
Fjernet ubrukt kode
Lagt til AzureAD sikkerhet på endepunkter med krav om saksbehandler gruppemedlemskap
Testet lokalt ad hoc med token generert av token-generator
> Kopiert AzureAD auth opplegget fra skribenten backend

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/BarnepensjonOmregnetNyttRegelverkDTO.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverk.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/InformasjonTilDegSomHandlerPaaVegneAvBarnet.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/InformasjonTilDegSomMottarPensjon.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmregnetBPNyttRegelverkDto.kt
hvis du sender inn noe annet får du rare resultater
> Over 18 år migrering barnepensjon - maler for bokmål

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverkFerdig.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/InformasjonTilDegSomMottarPensjon.kt
Det er selvfølgelig der de hører hjemme 🤦
> Legger inn vedlegg for ferdigstillingsmal også

- .github/workflows/deploy-web.yaml
- skribenten-web/bff/.nais/bff-dev.yaml
- skribenten-web/bff/.nais/nais.yaml
- validate-nais.sh
Endrer skribenten-web til å også bruke template, slik at det gjøres på samme måte i alle appene våre.
> Legg til skript for å validere nais-apper og endre skribenten-web til template

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/ufoer/Etteroppgjoer.kt
Endre "jf. folketrygdloven § 4-1." til "jf. forskrift om uføretrygd § 4-1."  på NB/NN-språklag, og tilsvarende på EN-språklag.
> Endre informasjon om forskriften i data class InntektOverInntektstak

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/avslag/AvslagFoerstegangsbehandling.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/Barnepensjon.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/KlageOgAnke.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/Fixtures.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonAvslagDTO.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/AvslagFoerstegangsbehandlingTest.kt
- Styrer innhold basert på bosattUtland og over/under 18 år
- Oppdaterer vedlegg basert på siste endringer i malen.
> Oppdaterer avslagsbrev for barnepensjon

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/BarnepensjonInnvilgelseNy.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/innvilgelse/BeregningAvBarnepensjon.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/BeregningAvOmstillingsstoenad.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonEndringHovedmalDTO.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelseNyDTO.kt
Legger til på barnepensjon. Justerer noe på omstillingsstønad.
> Legger til avsnitt for 4/5-regelen i innvilgelsesbrev barnepensjon

- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/routes/Brev.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/routes/tjenestebussintegrasjon/dto/BestillBrevDto.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/TjenestebussIntegrasjonService.kt
- tjenestebuss-integrasjon/src/main/kotlin/no/nav/pensjon/brev/tjenestebuss/tjenestebussintegrasjon/Routing.kt
- tjenestebuss-integrasjon/src/main/kotlin/no/nav/pensjon/brev/tjenestebuss/tjenestebussintegrasjon/services/arkiv/ArkivTjenestebussService.kt
Endrer til data klasse på extream bestilling response.  Returnerer alltid OK med feil istedenfor to ulike data klasser.
> Endrer til data klasse på extream bestilling response. 

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/avslag/BarnepensjonAvslag.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/Barnepensjon.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/avslag/AvslagFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/KlageOgAnke.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/TemplateResourceTest.kt
Tilbakekrevingsbiten i klage og anke-vedlegget gjenstår, men det får bli ein eigen PR. Det skal kun vera med for tilbakekrevingsvedtak, og det er jo eit separat arbeid vi må gjera, så reknar med det denne delen som ferdig.
> Oppdater mal for avslag barnepensjon

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/opphoer/BarnepensjonOpphoer.kt
Legger til vedlegg og bytter til ny "Har du spørsmål"
> Legger på vedlegg på barnepensjon opphør

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverk.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverkFerdig.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/migrering/DineRettigheterOgPlikterBP.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/migrering/InformasjonOmYrkesskade.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/migrering/InformasjonTilDegSomHandlerPaaVegneAvBarnet.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/migrering/InformasjonTilDegSomMottarBarnepensjon.kt
Ønsker å gjøre det tydeligere at disse hører til migrering og på sikt forsvinner.
> Flytter migreringsmaler for vedlegg ut til egen pakke

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/BarnepensjonOmregnetNyttRegelverkDTO.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverk.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverkFerdig.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmregnetBPNyttRegelverkDto.kt
Ref https://nav-it.slack.com/archives/C05F6TP0HJM/p1706272473892989
> Oppdatere migreringsbrev

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/avslag/OmstillingsstoenadAvslagRedigerbartUtfall.kt
Ønske fra saksbehandlere siden denne teksten gav de mye merarbeid. 
Godkjent endring fra fag. 
https://jira.adeo.no/browse/FAGSYSTEM-316227
> FAGSYSTEM-316227 Fjerne paragraf fra OMS avslagsbrev

- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/Routing.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/routes/Brevmaler.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/BrevmetadataService.kt
- skribenten-web/frontend/src/api/skribenten-api-endpoints.ts
- skribenten-web/frontend/src/routes/saksnummer_.$sakId.brevvelger.$templateId.tsx
- skribenten-web/frontend/src/routes/saksnummer_.$sakId.brevvelger.tsx
- skribenten-web/frontend/src/types/apiTypes.ts
Refaktorert henting av letterTemplates, og filtrer bort vedtaksbrev by default
> Filter vedtaksbrev

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocAlderspensjonFraFolketrygden.kt
> Updated text in AdhocAlderspensjonFraFolketrygden.kt

- .github/workflows/deploy-web.yaml
- .github/workflows/pdfbygger-brevbaker.yml
- .github/workflows/skribenten.yml
- .github/workflows/tjenestebuss-integrasjon.yml
Bump deploy@v2 and stop using api-deploy-tokens
> Bump deploy@v2

- skribenten-web/frontend/src/components/ApiError.tsx
- skribenten-web/frontend/src/main.tsx
- skribenten-web/frontend/src/routes/saksnummer_.$sakId.brevvelger.$templateId.tsx
- skribenten-web/frontend/src/routes/saksnummer_.$sakId.brevvelger.tsx
- skribenten-web/frontend/src/routes/saksnummer_.$sakId.tsx
> improve api error

- skribenten-web/frontend/src/components/select/SamhandlerSelect.tsx
- skribenten-web/frontend/src/hooks/usePreferredLanguage.tsx
- skribenten-web/frontend/src/routes/saksnummer_.$sakId.brevvelger.$templateId.tsx
- skribenten-web/frontend/src/types/apiTypes.ts
- skribenten-web/frontend/src/types/nameMappings.ts
Se design: https://www.figma.com/file/oUFhsO7YJUxDJeaWYKop30/%E2%9C%89%EF%B8%8F-Skribenten---MVP%2FPROTO?node-id=3027%3A28343&mode=dev
> Adresse redesign

- brevoppskrift-web/frontend/src/api/brevbaker-api-endpoints.ts
- brevoppskrift-web/frontend/src/api/brevbakerTypes.ts
- brevoppskrift-web/frontend/src/appStyles.css
- brevoppskrift-web/frontend/src/routeTree.gen.ts
- brevoppskrift-web/frontend/src/routes/index.tsx
- brevoppskrift-web/frontend/src/routes/template.$templateId.tsx
Kommer igang med visning. Ser foreløpig slik ut:
> Expreiment with brevoppskrift

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonRevurderingFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/common/Constants.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/omstillingsstoenad/OmstillingsstoenadFellesFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/omstillingsstoenad/OmstillingsstoenadForhaandsvarselFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/omstillingsstoenad/OmstillingsstoenadRevurderingFraser.kt
Endringer i nynorsk og engelsk oversettelse.
> EY-3359: Endringer etter testing av revurdering for omstillingsstønad

- skribenten-web/frontend/src/Brevredigering/LetterEditor/LetterEditor.cy.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/EditorMenu.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/example-letter-1.json
Skriv litt mer nøye cypress tester for navigering
> Improve cypress tests

- pdf-bygger/.nais/nais.yaml
- pensjon-brevbaker/.nais/nais.yaml
- tjenestebuss-integrasjon/.nais/nais.yaml
For å kunne følgje kall heile vegen gjennom distribuert sporing i Grafana (via OpenTelemetry)
For vår (etterlatte) sin del ønskjer vi å kunne slå opp og sjå mest mogleg data om våre kall, kor lang tid dei tar og alt sånt.
Ref https://doc.nais.io/how-to-guides/observability/auto-instrumentation/
> Skrur på observability

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocGjenlevendEtter1970.kt
New adhoc letter with text amendments.
> NN text amendments

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/varsel/OmstillingsstoenadVarselAktivitetsplikt.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/varsel/OmstillingsstoenadVarselAktivitetspliktRedigerbartUtfall.kt
> Liten tekstendring i varselbrevet

- skribenten-web/frontend/cypress/e2e/brevvelger.cy.ts
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-BrevmalDoksys.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-BrevmalExstream.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-EBlankett.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-SelectLanguage.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-TemplateUtils.ts
- skribenten-web/frontend/src/types/Nullable.ts
- skribenten-web/frontend/src/types/apiTypes.ts
gjerne se på https://github.com/navikt/pensjonsbrev/pull/782 først
> Fjern språkvalg ved notat

- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/route.tsx
key points:
- fetchQuery (som var brukt tidligere) vil alltid hente en ny, og sette inn i cache
- ensureQueryData henter fra cache, hvis den er tom, gjør en ny fetch. 
- Disse 2 kan brukes inne i loader for routes
- useQuery vil hente og subscribe til endringer - Hvis denne kombineres med ensureQueryData i loaderen, vil det foretrukkede språket alltid være valgt.
> ved endring av template, skal rendringen skje responsivt

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/aktivitetsplikt/OmstillingstoenadAktivitetspliktInformasjon4mndInnhold.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/varsel/OmstillingsstoenadVarselAktivitetspliktRedigerbartUtfall.kt
Mindre justeringer på infobrev v/ 4 mnd og varsel om stans.
[EY-4135](https://jira.adeo.no/browse/EY-4135)
> Tekstendringer i brev om aktivitetsplikt

- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/letter/EditedLetterVisitor.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/letter/UpdateEditedLetter.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/letter/VariableValuesVisitor.kt
- skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/letter/UpdateEditedLetterTest.kt
Variabler som flyttes til nye blokker ble ikke oppdatert med nye verdier
> Fiks arveløse variabler

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonFellesFraser.kt
> Endrer til tre uker / three weeks over alt.

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/informasjon/OmstillingsstoenadInnhentingAvOpplysninger.kt
> Tar i bruk eksisterende funksjon for postadresse

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/informasjon/BarnepensjonMottattSoeknad.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/informasjon/OmstillingsstoenadMottattSoeknad.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInformasjonMottattSoeknad.kt
Få med datoen i teksten siden tittelen forsvinner.
> Justering av mottatt søknad brev.

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/Beregningsperiodetabell.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoenadInnvilgelse.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoenadRevurdering.kt
> Informasjon om institusjonsopphold i beregningstabellen

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/aktivitetsplikt/OmstillingsstoenadAktivitetspliktInformasjon4mndInnhold.kt
https://jira.adeo.no/browse/EY-4292
> Endre Krav til aktivitet ved mottak av omstillingss brødtekst

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/aktivitetsplikt/OmstillingsstoenadAktivitetspliktInformasjon4mndInnhold.kt
> Mindre justering av tekster i OMS aktivitetsplikt v/ 4 måneder

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/VedleggOpplysningerOmEtteroppgjoeret.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/OpplysningerOmEtteroppgjoeret.kt
> Updated text in data class OmBeregningAvUfoeretrygd

- docker-compose.yml
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/Routing.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/routes/Sak.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/SafService.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/ServiceResult.kt
- skribenten-backend/src/main/resources/application-local.conf
- skribenten-backend/src/main/resources/application.conf
- skribenten-backend/src/main/resources/saf/graphql.config.yml
- skribenten-web/frontend/cypress/e2e/brevbehandler.cy.ts
- skribenten-web/frontend/src/api/sak-api-endpoints.ts
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brev.$brevId.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevbehandler/-components/BrevbehandlerMeny.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevbehandler/-components/FerdigstillBrev.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevbehandler/-components/PDFViewerTopBar.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevbehandler/route.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/kvittering/-components/KvitterteBrev.tsx
https://github.com/navikt/pensjonsbrev/pull/869
> Henter original pdf fra journalpost når et brev distribueres som lokalprint

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonForeldreloesFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonInnvilgelseFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/omstillingsstoenad/OmstillingsstoenadInnvilgelseFraser.kt
Gjelder både OMS og BP, ref. EY-4360 og EY-4361
>  EY-4360 og EY-4361 Paragrafen for etterbetaling skal være med i innvilgelse

- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/EditorMenu.tsx
Fjerner at ikonet vises som lagret ved sidelast
> fjerner første ikon lasting i editormenu ved sidelast

- skribenten-web/frontend/cypress/e2e/brevbehandler.cy.ts
- skribenten-web/frontend/src/Brevredigering/LetterEditor/LetterEditor.cy.tsx
- skribenten-web/frontend/src/api/sak-api-endpoints.ts
- skribenten-web/frontend/src/api/skribenten-api-endpoints.ts
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevbehandler/-components/BrevbehandlerMeny.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevbehandler/-components/FerdigstillBrev.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevbehandler/route.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-components/endreMottaker/EndreMottaker.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-components/endreMottaker/EndreMottakerUtils.ts
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-components/endreMottaker/HentOgVisSamhandlerAdresse.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-components/endreMottaker/OppsummeringAvValgtMottaker.tsx
- skribenten-web/frontend/src/types/AdresseUtils.ts
- skribenten-web/frontend/src/types/brev.ts
- skribenten-web/frontend/test/modules/LetterEditor/utils.ts
Burde se på om vi kan fjerne et av adresse-typene som vi har i frontend. Samtidig se på om vi kan forenkle deler av samhandler-greiene videre.
> Endre mottaker for brevbehandler

- skribenten-web/frontend/cypress/e2e/brevredigering.cy.ts
- skribenten-web/frontend/cypress/fixtures/modelSpecificationOrienteringOmSaksbehandlingstid.json
- skribenten-web/frontend/cypress/fixtures/orienteringOmSaksbehandlingstidResponse.json
- skribenten-web/frontend/cypress/fixtures/orienteringOmSaksbehandlingstidResponseMedSoknadOversendesTilUtlandet.json
- skribenten-web/frontend/src/Brevredigering/ModelEditor/components/ScalarEditor.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brev.$brevId.tsx
Setter opp en PR mens jeg lager test
> implement boolean for scalarEditor

- skribenten-web/frontend/cypress/e2e/brevredigering.cy.ts
- skribenten-web/frontend/cypress/fixtures/brevResponse.json
- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/SignaturView.tsx
- skribenten-web/frontend/src/Brevredigering/ModelEditor/ModelEditor.tsx
- skribenten-web/frontend/src/Brevredigering/ModelEditor/components/ScalarEditor.tsx
- skribenten-web/frontend/src/api/brev-queries.ts
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brev.$brevId.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brev.index.tsx
legger opp en PR - må fikse et par små ting
> Kan legge på signatur på brev

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/informasjon/BarnepensjonInformasjonDoedsfallMellomAttenOgTjueVedReformtidspunkt.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonFellesFraser.kt
Siden dette er såpass få brev, lager jeg en manuell punktliste for brev. Forrige endring må reverseres siden uthevet tekst ikke fungerte.
> Ny styling på liste

- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/$templateId/-components/BrevmalBrevbaker.tsx
Her kunne vi nok generalisert formet på en eller annen måte
> fiks rekkefølgen av inputs i brevmal brevbaker

- skribenten-web/frontend/src/Brevredigering/LetterEditor/LetterEditor.cy.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/LetterEditor.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/EditorMenu.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/SakspartView.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/editor.css
- skribenten-web/frontend/src/Brevredigering/LetterEditor/utils.ts
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brev.$brevId.tsx
baserer seg på https://github.com/navikt/pensjonsbrev/pull/944
> Design endringer brevredigering & keyboard shortcuts for tekststil

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonRevurderingFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/omstillingsstoenad/OmstillingsstoenadRevurderingFraser.kt
Endrer følgende:
- Revurderingsbrev OMS og BP
- Opphørsbrev OMS og BP
> EY-4462: Endrer på tekst ved feilutbetaling uten varsel - trekkes annen ytelse

- pensjon-brevbaker-api-model/build.gradle.kts
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/legacy/PE.kt
1. publiserer ny api-modell.
2. pesys sender ekstra data
3. brevbaker bruker ekstra data i brev.
> Api-model for å legge til ekstra felt.

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/omstillingsstoenad/OmstillingsstoenadInnvilgelseFraser.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/innvilgelse/OmstillingsstoenadInnvilgelse.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/innvilgelse/OmstillingsstoenadInnvilgelseRedigerbartUtfall.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoenadInnvilgelse.kt
Avdød brukes ikke, så fjerner den fra dto
> EY-4596: Fjern avdød som ikke brukes i redigerbart utfall

- skribenten-web/frontend/cypress/e2e/brevvelger/brevvelger.cy.ts
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/-components/brevmal/components/SelectEnhet.tsx
Verdien var lagt inn riktig i formet, men selecten reflekterte ikke dette.
> enhetsId select gjenspeiler enhetsId i formet

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/revurdering/BarnepensjonRevurdering.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/revurdering/BarnepensjonRevurderingRedigerbartUtfall.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonRevurdering.kt
Avhengig av endringer fra denne: https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/6322
> EY-4625: Endrer rekkefølge på avsnitt revurdering BP

- .github/workflows/codeql.yml
Tatt ganske direkte frå [den tilsvarande eg sette opp for etterlatte](https://github.com/navikt/pensjon-etterlatte-saksbehandling/blob/main/.github/workflows/codeql.yml)
Køyring: https://github.com/navikt/pensjonsbrev/actions/runs/11833949513
> CodeQL-scanning

- pdf-bygger/.nais/prod.yaml
Vil merges i 3-4 tiden avhengig av når behandlingene skal kjøres i dag
> Oppskalering for "batch"-kjøring

- pdf-bygger/.nais/prod.yaml
Reverts navikt/pensjonsbrev#1087
Merger denne når jeg har fått melding om at batch-kjøring er ferdig
> Batch-kjøring ferdig, reverter oppskalinger pdf-bygger

- .github/workflows/cleanup.yml
- .github/workflows/pdfbygger-brevbaker.yml
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/ApplicationITest.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/IntegrationTestUtils.kt
Ser bra ut lokalt, håper GHA er einig
> Unngå å køyre opp brevbaker-container i integrasjonstestane

- brevoppskrift-web/bff/package-lock.json
- brevoppskrift-web/bff/package.json
- brevoppskrift-web/bff/src/frontendRoute.ts
- brevoppskrift-web/bff/src/server.ts
Både nais-konsollet og GitHub security rapporterer om sårbarheiter, så får dei ut av verda.
Startar med brevoppskrift, men mykje av dette kan også gjerast omtrent identisk på skribenten-bffen etterpå.
> Oppgradere brevoppskrift

- .github/workflows/pdfbygger-brevbaker.yml
- pensjon-brevbaker/README.md
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/TemplateModelSpecificationFactory.kt
Readme for å køyre brevbaker utan å ha tilgang til våre secrets
> Brevbaker utan secrets-readme

- .github/dependabot.yml
Dette er ein redigert versjon av den vi hadde for etterlatte. Har ikkje fått testa den i dette repoet, det er overraskande knotete å få køyrd dependabot frå eiga grein, så trur det lettaste er å ta det inn i main og så iterere. Skadar jo uansett lite.
> Dependabot-konfig

- .github/dependabot.yml
Nokre oppdateringar bør sjåast samla, andre litt separert, basert på PR-ane dependabot laga i stad
> Dependabot-gruppering

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/redigerbar/ForhaandsvarselVedTilbakekreving.kt
Rettet kategori til FEILUTBETALING
> Rettet kategori til FEILUTBETALING i ForhaandsvarselVedTilbakekreving.kt

- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/EditorBulletList.tsx
- skribenten-web/frontend/src/appStyles.css
- skribenten-web/frontend/src/routes/__root.tsx
- skribenten-web/frontend/src/routes/saksnummer.index.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/route.tsx
Dette skal fikse at vi får den horisontale scrollbaren over knappene på bunnen.
Derimot, så har vi en annen scrollbar som vises i brevvelger accordion. Antar den kommer til å være vanskeligere å fikse uten å faktisk ha appen kjørende i VMware 🤔
> Fiks horisontal scrollbar ved bruk av SKSS

- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/CommonEnums.kt
Opprettet companion object "val pensjon" for enum class Sakstype i CommonEnums.kt
> Opprettet companion object "val pensjon" 

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/BeregningAvBarnepensjon.kt
…siden den nå alltid er satt i requester fra Gjenny.
> EY-4918: BarnepensjonBeregningsperiode.harForeldreloessats gjøres non-nullable

- skribenten-web/frontend/package-lock.json
- skribenten-web/frontend/package.json
skal fikse https://github.com/navikt/pensjonsbrev/security/dependabot/54
Usikker på hvorfor vi trengte å override den til å begynne med, men det ser ikke ut som at det skal være nødvendig lenger
> fjerner rollup override

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/aktivitetsplikt/OmstillingsstoenadAktivitetspliktInformasjon4mndInnhold.kt
Rette scenario som ikke har blitt testet tidligere som nå viser seg å inneholde feil
> EY-4913 skjule avsnitt ved null utbetaling aktivitetsplikt4mnd

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/FeatureToggles.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/Fixtures.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/maler/example/LetterExample.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/GenererAlleMaleneTest.kt
Fekk feilmeldinga `java.lang.IllegalArgumentException: Unable to calculate stableHashCode for type class no.nav.pensjon.brev.UnleashToggle`
> Fiks toggling også inne i paragraph

- skribenten-backend/build.gradle.kts
- skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/services/BrevredigeringServiceTest.kt
Trur vi bør få testa det vi skal sjølv utan denne.
> Nedgraderer Postgres-avhengnad til ein stabil versjon

- .github/workflows/deploy-brevoppskrift-web.yaml
- .github/workflows/deploy-skribenten-web.yaml
- .github/workflows/pdfbygger-brevbaker.yml
- .github/workflows/skribenten.yml
- .github/workflows/tjenestebuss-integrasjon.yml
Ref https://nav-it.slack.com/archives/C01DE3M9YBV/p1737982464376109
> Tar bort variablar som ikkje lenger er nødvendige for nais-action

- skribenten-web/frontend/src/Brevredigering/LetterEditor/actions/switchFontType.ts
- skribenten-web/frontend/src/Brevredigering/LetterEditor/actionsTest/switchFontType.cy.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/EditorFonts.tsx
legger på TODO for endring av variabler
> rydd opp i switchFontType

- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/EditorMenu.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/route.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/kvittering/-components/Oppsummeringspar.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/route.tsx
Trenger ikke å vise vedtaksId i subheaderen ifølge Karoline. Får legge den tilbake hvis dem savner det.
> ny subheader med små design fixes

- skribenten-web/frontend/src/Brevredigering/LetterEditor/LetterEditor.cy.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/LetterEditor.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/actionsTest/switchTypography.cy.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/SakspartView.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/components/SignaturView.tsx
- skribenten-web/frontend/src/Brevredigering/LetterEditor/editor.css
- skribenten-web/frontend/src/Brevredigering/LetterEditor/utils.ts
baserer seg på https://github.com/navikt/pensjonsbrev/pull/1250
> Oppdater størrelser og avstand i brev

- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/BarnepensjonInnvilgelse.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/BarnepensjonInnvilgelseForeldreloes.kt
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/innvilgelse/OmstillingsstoenadInnvilgelse.kt
- pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelse.kt
Se relatert PR i gjenny 
https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/6994
> EY-3821 legge til støtte for omgjøring av vedtak på avslag

- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/-components/endreMottaker/BekreftAvbrytelse.tsx
Body text size fra small -> medium
> Endret body tekst size i bekreftelsemodalen 

- skribenten-web/frontend/eslint.config.mjs
> Fiks tsconfig path in eslint config slik at den

- brevoppskrift-web/bff/.npmrc
- skribenten-web/bff/.npmrc
Ref https://sikkerhet.nav.no/docs/sikker-utvikling/tredjepartskode#begrense-handlingsrommet-til-tredjeparter
> Skrur på ignore scripts for bffs

- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/alder/AvslagUttakFoerNormertPensjonsalderAuto.kt
> Vedlegg lista kommer automatisk med i brevet. Trenger ikke være med i outline.

- etterlattemaler/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/BeregningAvBarnepensjon.kt
- etterlattemaler/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/BeregningAvOmstillingsstoenad.kt
Viser avsnitt om 4/5-regelen ved beregning hvor beregningsmetode prorata er benyttet.
> EY-5065: Legger til avsnitt for 4/5-regelen ved prorata-beregning

- pensjon-brevbaker-api-model/gradle.properties
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/redigerbar/VarselRevurderingAvPensjon.kt
- pensjonsmaler/build.gradle.kts
- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/redigerbar/VarselRevurderingAvPensjon.kt
- pensjonsmaler/src/test/kotlin/no/nav/pensjon/brev/fixtures/redigerbar/VarselRevurderingAvPensjonDto.kt
- pensjonsmaler/src/test/kotlin/no/nav/pensjon/brev/maler/redigerbar/VarselRevurderingAvPensjonTest.kt
Ta i bruk rullegardin for tittelValg
> Bumped api-version til 140, endret VarselRevurderingAvPensjonDto.kt

- pensjon-brevbaker-api-model/src/test/kotlin/no/nav/pensjon/brev/api/model/maler/BrevkodeTest.kt
- pensjonsmaler/src/test/kotlin/no/nav/pensjon/brev/template/GenererAlleMaleneTest.kt
Test på om alle maler bruker sine egne unike brevkoder, og at en brevkode ikke eksisterer på tvers av autobrev/redigerbare brev.
> Test på om alle maler bruker sine egne unike brevkoder

- pensjon-brevbaker-api-model/gradle.properties
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/alderApi/AvslagUttakFoerNormertPensjonsalderAutoDto.kt
- pensjonsmaler/build.gradle.kts
- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/alder/vedlegg/OpplysningerBruktIBeregningenAP2016Vedlegg.kt
- pensjonsmaler/src/test/kotlin/no/nav/pensjon/brev/fixtures/alder/AvslagUttakFoerNormertPensjonsalderAutoAP2016Dto.kt
Co-authored-by: Espen Schei <espen.schei@nav.no>
> Legger til trygdetid for kap19 i 2016 brev

- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/redigerbar/InformasjonOmSaksbehandlingstid.kt
Uføre har egen tilsvarende mal.
> Fjerner informasjon om saksbehandlingstid fra uføre-kontekst. 

- pensjon-brevbaker-api-model/gradle.properties
- pensjonsmaler/build.gradle.kts
> Bumped api-modell til 166

- .github/workflows/verify-brevoppskrift-web.yaml
- brevoppskrift-web/bff/package-lock.json
- brevoppskrift-web/bff/package.json
- brevoppskrift-web/bff/src/actuators.ts
- brevoppskrift-web/bff/src/frontendRoute.ts
Oppdaga at verify-jobben som køyrer på PRs her ikkje sjekka bff-en, så bygg gjekk fint gjennom der, men feila når det kom til main.
> Sjekkar bff for brevoppskrift på samme måte som vi gjer for skribenten

- pdf-bygger/.nais/prod.yaml
Ref https://nav-it.slack.com/archives/C05C8SNN78X/p1746438909173899?thread_ts=1745913697.600679&cid=C05C8SNN78X
> Skalerer opp pdfbygger midlertidig

- etterlattemaler/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/etteroppgjoer/EtteroppgjoerForhaandsvarsel.kt
- etterlattemaler/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/etteroppgjoer/EtteroppgjoerForhaandsvarselInnhold.kt
- etterlattemaler/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/EtteroppgjoerForhaandsvarselDTO.kt
> EY-5230 legge til redigerbar del for forhåndsvarsel eo oms

- skribenten-web/bff/src/internalRoutes.ts
- skribenten-web/bff/src/server.ts
- skribenten-web/frontend/src/api/bff-endpoints.ts
- skribenten-web/frontend/src/components/ApiError.tsx
- skribenten-web/frontend/src/routes/index.tsx
- skribenten-web/frontend/src/utils/logger.tsx
Dette er ein forenkla variant av [Gjenny-måten å gjera det på](https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/382).
Poenget er at frontenden sender til bff-en, som så loggar det ut.
> Logg feil som skjer i frontend

- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/redigerbar/InformasjonOmGjenlevenderettigheter.kt
Ref https://nav-it.slack.com/archives/G014A7H6DCN/p1748871738708049?thread_ts=1748864529.234199&cid=G014A7H6DCN og https://nav-it.slack.com/archives/G014A7H6DCN/p1748948716038119?thread_ts=1748864529.234199&cid=G014A7H6DCN
> Forenklar brevet om gjenlevenderettigheter ved å fjerne sakstypar og tillegg som ikkje lenger er relevante her

- etterlattemaler/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/etteroppgjoer/EtteroppgjoerForhaandsvarselInnhold.kt
- rette rettsgebyr dato gjeldende
> Rette feil brev etteroppgjør etter demo

- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/common/Constants.kt
- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/common/Felles.kt
- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/redigerbar/VarselRevurderingAvPensjon.kt
Diverse endringer/rettelser i VarselRevideringAvPensjon (MF_000156)
> Diverse endringer/rettelser

- brevoppskrift-web/bff/.nais/nais.yaml
Fint å ha dette skrudd på, og likt, overalt.
> Skrur på observability og logging også for brevoppskrift

- brevbaker-dsl/api/brevbaker-dsl.api
- brevbaker-dsl/src/main/kotlin/no/nav/pensjon/brev/template/Operations.kt
- brevbaker-dsl/src/main/kotlin/no/nav/pensjon/brev/template/dsl/expression/Base.kt
- brevbaker-dsl/src/main/kotlin/no/nav/pensjon/brev/template/dsl/expression/Collection.kt
- brevbaker-dsl/src/main/kotlin/no/nav/pensjon/brev/template/dsl/expression/Legacy.kt
- brevbaker-dsl/src/main/kotlin/no/nav/pensjon/brev/template/dsl/expression/Number.kt
- brevbaker-dsl/src/test/kotlin/no/nav/pensjon/brev/template/ExpressionEvalTest.kt
- brevbaker-dsl/src/test/kotlin/no/nav/pensjon/brev/template/dsl/expression/ExpressionTest.kt
- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/common/Felles.kt
- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/legacy/LegacyFunksjoner.kt
Litt lettere syntaks for å kalle operations på expressions
> Gjør Expression operations kallbare som funksjoner

- docker-compose.yml
- pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/FeatureToggleHandler.kt
- pensjon-brevbaker/src/main/resources/application-local.conf
Pluss betre logging frå Unleash ved manglande brytarar
> application-local i docker-compose også for brevbaker

- skribenten-backend/build.gradle.kts
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/SkribentenApp.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/letter/EditModel.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/letter/UpdateEditedLetter.kt
- skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/BrevbakerService.kt
- skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/auth/AuthorizeAnsattSakTilgangTest.kt
- skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/letter/EditModelJacksonTest.kt
- skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/services/BrevbakerServiceTest.kt
- skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/services/BrevmalServiceTest.kt
- skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/services/BrevredigeringServiceTest.kt
- skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/services/FakeServices.kt
- skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/services/LegacyBrevServiceTest.kt
Bytter også ut `TODO(...)` i stubs siden de kommer opp i Todos-listen i intellij.
> Skribenten: Fjern tittel som string kompatibilitet

- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/redigerbar/InnvilgelseAvAlderspensjon.kt
Ref denne tråden: https://nav-it.slack.com/archives/C08H52KFD4Y/p1756126977970389
> Rettar feil rekkjefølgje og tar bort utdatert tekst

- pensjon-brevbaker-api-model/gradle.properties
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/redigerbar/VedtakEndringAvAlderspensjonFordiOpptjeningErEndretDto.kt
- pensjonsmaler/build.gradle.kts
- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/redigerbar/VedtakEndringAvAlderspensjonFordiOpptjeningErEndret.kt
- pensjonsmaler/src/test/kotlin/no/nav/pensjon/brev/maler/redigerbar/VedtakEndringAvAlderspensjonFordiOpptjeningErEndretDto.kt
Ref https://nav-it.slack.com/archives/C08H52KFD4Y/p1756459351123389?thread_ts=1756205934.839429&cid=C08H52KFD4Y og resten av tråden.
> Tar bort tekst om skjermingstillegg som ikkje lenger er relevant

- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brev.$brevId.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevbehandler/route.tsx
Og gjør om scrolling i brevbehandler til auto, dvs. vis scrollbar hvis overflow, skjul scrollbar hvis ikke.
> Legg til scrolling i brevredigeringsmeny

- skribenten-backend/src/main/resources/db/migration/V6__kryptering.sql
Ved å ta det i separat PR kan vi deploye endrings-greina i dev, og så gå tilbake til main etterpå, utan at det blir krøll på noko vis.
Tilrettelegging for https://github.com/navikt/pensjonsbrev/pull/1781
> Innfører dei nye databasekolonnene vi skal bruke til kryptering.

- alder-brevbaker-api-model/gradle.properties
- alder-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/Aldersbrevkoder.kt
- alder-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/auto/InfoAldersovergangEps60AarAutoDto.kt
- aldersmaler/build.gradle.kts
- aldersmaler/src/main/kotlin/brev/AlderTemplates.kt
- aldersmaler/src/main/kotlin/brev/auto/InfoAldersovergangEps60AarAuto.kt
- aldersmaler/src/test/kotlin/brev/Fixtures.kt
Informasjon til deg som har ektefelle/partner/samboer som snart fyller 60 år
> Konverterer infobrevet mf-000238 til brevbaker

- alder-brevbaker-api-model/gradle.properties
- alder-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/Aldersbrevkoder.kt
- alder-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/auto/InfoAldersovergangEps62AarAutoDto.kt
- aldersmaler/build.gradle.kts
- aldersmaler/src/main/kotlin/brev/AlderTemplates.kt
- aldersmaler/src/main/kotlin/brev/auto/InfoAldersovergang67AarSaerskiltSatsAuto.kt
- aldersmaler/src/main/kotlin/brev/auto/InfoAldersovergangEps60AarAuto.kt
- aldersmaler/src/main/kotlin/brev/auto/InfoAldersovergangEps62AarAuto.kt
- aldersmaler/src/main/kotlin/brev/felles/Constants.kt
- aldersmaler/src/test/kotlin/brev/Fixtures.kt
Informasjon til deg som har ektefelle/partner/samboer som snart fyller 62 år
> Konverterer infobrevet mf-000240 til brevbaker

- aldersmaler/src/test/kotlin/brev/template/GenererAlleMaleneTest.kt
, no når alder har brev i modulen sin
> Skrur på testen som genererer opp html for alle brev for alder

- pensjon-brevbaker-api-model/gradle.properties
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/CommonEnums.kt
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/alderApi/OmregningAlderUfore2016Dto.kt
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/redigerbar/VedtakEndringVedFlyttingMellomLandDto.kt
- pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/redigerbar/VedtakStansAlderspensjonFlyttingMellomLandDto.kt
- pensjonsmaler/build.gradle.kts
Første av fleire PR-ar i rekka.
> Introduserer enum for å velje informasjon om medlemskap-vedlegg

- skribenten-web/frontend/.gitignore
- skribenten-web/frontend/cypress/e2e/brevredigering/autolagring.cy.ts
- skribenten-web/frontend/src/api/brev-queries.ts
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/attester.$brevId/redigering.tsx
- skribenten-web/frontend/src/routes/saksnummer_/$saksId/brev.$brevId.tsx
Bytt til oppdaterBrev(redigertBrev, saksebehandlerValg) ved lagring av saksbehandlervalg.
> Fiks at autolagring av tekstendring overlever manuelt saksbehandlervalg

- pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/redigerbar/VedtakStansAlderspensjonFlyttingMellomLand.kt
Skal ikke sjekke at både eksportforbud og eksportforbud for avdød er satt. EqualTo garderer mot null også, så det går fint.
> Logisk glipp.
