navikt/pensjonsbrev

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/EksempelBrev.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/OmsorgEgenAuto.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/LetterTemplate.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/dsl/Template.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/LanguageTest.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/base/PensjonLatexITest.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/dsl/ShowIfTest.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/dsl/TemplateTableTest.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/dsl/TemplateTest.kt

Pga. endringen hvor type-parameteren Lang er kovariant så tillot createTemplate funksjonen at man sender inn `lang = languages(Bokmal, Nynorsk), title = newText(Bokmal to "")`. Da vil typen til malen bli LangBokmal, men LanguageCombination objektet vil svare runtime at malen er LangBokmalNynorsk.

Fiks problem hvor createTemplate tillot feil deklarering av språk

---

README.md
pensjon-brevbaker-api-model/build.gradle.kts
pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/vedlegg/MaanedligUfoeretrygdFoerSkatt.kt

splitt felter i ufoeretrygdPeraMaaned i netto og brutto for å kunne gjenbruke eksisterende tolkninger i pesys.

splitt felter i ufoeretrygdPeraMaaned i netto og brutto.

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/UngUfoerAuto.kt

Vedlegget skal ikke inkluderes om det kun er uavkortet uføretrygd som utbetales i en periode.

Bruker riktig verdi ved filtrering av vedlegg. 

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/Operations.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/dsl/expression/Collection.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/OperationsTest.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/template/dsl/expression/CollectionTest.kt
skribenten-backend/build.gradle.kts
skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/BrevbakerService.kt

Legger til støtte for å kunne transformere elementene i en liste:
```
// Gitt -  datoer: Expression<List<LocalDate>>
val datoStrenger: Expression<List<String>> = datoer.map(BinaryOperation.LocalizedDateFormat)
```
Legger til støtte for å liste opp alle elementene i en liste med komma og "og"/"and"
```
// Gitt - navn: Expression<List<String>> 
val alleNavn: Expression<String> = navn.format()
```
Dette kan brukes sammen slik:
```
val alleDatoer = datoer.map(BinaryOperation.LocalizedDateFormat).format()
text(
Bokmal to "Vi er åpne på følgende datoer: ".expr() + alleDatoer,
English to "We are open on these dates: ".expr() + alleDatoer,
)
```

Legg til collection mapping og lokalistert opplisting

---

pensjon-brevbaker-api-model/build.gradle.kts
pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/vedlegg/OpplysningerBruktIBeregning.kt
pensjon-brevbaker/build.gradle.kts
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/OpphoerBarnetilleggAuto.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/opplysningerbruktiberegningufoere/TabellUfoereOpplysninger.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/OpplysningerBruktIBeregningUT.kt
skribenten-backend/build.gradle.kts

Bytter om rekkefølge på vedlegg, korrekt visning av faktisk trygdetid norge, påkrever ikke inntekt etter uføre(saker konvertert fra uførepensjon har ikke det) og refactoring.

PL-5105: bugfix

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/OpphoerBarnetilleggAuto.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/ufoer/Ufoeretrygd.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/opplysningerbruktiberegningufoere/TabellUfoereOpplysninger.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/vedlegg/OpplysningerBruktIBeregningUT.kt

* retter feil i "skatt for deg som bor i utlandet" visnings-logikk
* viser kun sivilstand når det er relevant i tabellen (bruker har minsteytelse)
* kun vis tekst om utbetaling av uføretrygd om du får utbetalt uføretrygd.

PL-5105: Rettinger etter test.

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/Barnepensjon.kt

Dette gjorde at tabellen ikke ble med i brevene. Feilen ser ut til å ha blitt innført 27. juli i samme fil som i commiten her.

EY-2530 Legger inn includePhrase rundt beregningstabellen, noe som manglet

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/ny/BarnepensjonInnvilgelseEnkel.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/innvilgelse/BarnepensjonInnvilgelseEnkelFraser.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/EtterbetalingAvBarnepensjon.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/Etterbetaling.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonEndringHovedmalDTO.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelseEnkelDTO.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelseNyDTO.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OMSInnvilgelseDTO.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OMSInnvilgelseFoerstegangsvedtak.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OMSRevurdering.kt

Vi har avklart med fag (Merethe og Liv Inger) at tabellen for kva periodar som er etterbetaling skal ut, og tabellen i vedlegg 1 (Slik har vi beregnet pensjonen din) skal ha alle.
Skal vera likt for både BP og OMS.

EY-2646: Forenkle DTO for etterbetaling

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/Trygdetidstabell.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/BeregningAvBarnepensjon.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelseNyDTO.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OMSInnvilgelseFoerstegangsvedtak.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OMSRevurdering.kt

Rydder også opp i periode: Vi kan ikke sende en allerede mappet tekst på norsk for å angi et intervall med år, måneder og dager

EY-2926 Trygdetidstabellen skal vises kun hvis vi har perioder

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/endring/EndringHovedmal.kt

Feiler ved revurdering hvor man ikke huker av for etterbetaling nå. Dette må være mulig.

EY-3080 Setter etterutbetaling til å være ikke obligatorisk

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverk.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/ForhaandsvarselOmregningBP.kt

Direkte lagt inn frå malen: https://confluence.adeo.no/display/TE/Brevmaler+-+Nytt+regelverk+%28NBP%29+Barnepensjon
Sjølve omsetjinga kjem frå kommunikasjonsavdelinga, PR-en her går på at det er lagt inn på rett plass

Legg inn nynorskomsetjinga av førehandsvarselet

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/BarnepensjonOmregnetNyttRegelverkDTO.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverk.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/ForhaandsvarselOmregningBP.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/Trygdetidstabell.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmregnetBPNyttRegelverkDto.kt

Hvis foreldreløs inneholder vedtaksbrevet tekster som skal slettes i endelig vedtak. Forhåndsvarselet trenger ikke å redigeres av saksbehandler

Foreldreløs forhåndsvarsel + migreringsbrev

---

pensjon-brevbaker/.nais/dev.yaml
pensjon-brevbaker/.nais/nais.yaml
pensjon-brevbaker/.nais/prod.yaml

Inntil vi har oppsett på AD-gruppe hadde det vært nice å tillate allUsers for brevbaker i dev. Så jeg slipper dispatche den på ny hver gang noe deployes 🙏

allowAllUsers in dev for brevbaker for now

---

skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/Database.kt

Setter max pool size til 4 for å unngå å bruke opp alle connections ved deployment hvor det er 4 aktive pods. Det kan gå inntil 6 connections til diverse nais admin greier. Da vil vi bruke 21/25 connections under deployment, og det er greit å ha noen reserve i tilfelle noen er koblet til databasen. 8 Connections spredd på to instanser bør være nokk til å serve saksbehandlere. Ellers må vi se på å velge en større postgres instans.

Setter max pool size til 4 for å unngå å bruke opp alle connections

---

README.md
docker-compose.yml

Legger til tomme env files slik at docker-compose ikke feiler når du prøver å kjøre brevbaker/pdf-bygger. Dette skjer fordi docker påkrever alle env-files selv om skribenten-profilen ikke er valgt.

Bugfix lag tomme env files

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/ElementTilBrevbakerkonvertering.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoenadInnvilgelse.kt

Tidligere la vi lister på innsiden av paragrafer når vi konverterte til Slate, men det fungerer ikke ved redigering av lister.

Punktlister konverteres nå riktig når dem er på et format som kan endres på i Gjenny

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/DineRettigheterOgPlikter.kt

- Fjerner avsnitt som er duplikat. Dette lå på bunn av punktlista i barnepensjon, men har fått egen overskrift for OMS.
- Fikser manglende ord i avsnitt om innsyn.
- Legger også til oversettelser der vi har det. Mangler fortsatt et par avsnitt for å ha nynorsk og engelsk på plass.

Fjerner duplikat avsnitt og legger til manglende ord

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/revurdering/OmstillingsstoenadRevurdering.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoenadRevurdering.kt

Fjerner noen deprecated'e typer fra brevet for revurdering av omstillingsstønad. Brevet er forøvrig ikke klart for bruk i produksjon ennå.

Klargjør typer for revurdering av omstillingsstønad

---

skribenten-web/frontend/src/routes/saksnummer_.$sakId.brevvelger.$templateId.tsx

Hvis adresse oppslag feilet så boblet error opp til siste route match. Vil heller at feilen fanges lokalt der den brukes

local catchboundary

---

skribenten-web/frontend/src/components/ApiError.tsx
skribenten-web/frontend/src/routes/saksnummer_.$sakId.brevvelger.$templateId.tsx

Å bruke Errorboundary og Await komponenten ser fine and dandy ut i dokumentasjonen, men i praksis visste det seg at feilen som blir kastet mister kontekst at det er en axiosError, som gjorde det mer kronglete å vise feilmelding på en logisk måte. Reverter derfor det eksperimentet

use traditional load/data/error instead of suspense and error boundaries

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/template/render/LanguageSettings.kt

Ref denne [EY-3543](https://jira.adeo.no/browse/EY-3543), så har vi nå fått klarsignal at engelsk oversettelse for "saksbehandler" skal endres fra "Assesor" til "Caseworker"

Endre engelsk tittel til caseworker for saksbehandler

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/avslag/BarnepensjonAvslag.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/opphoer/BarnepensjonOpphoer.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/klage/AvvistKlageFerdigstilling.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/avslag/OmstillingsstoenadAvslag.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/opphoer/OmstillingsstoenadOpphoer.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/tilbakekreving/TilbakekrevingFerdig.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/tilbakekreving/TilbakekrevingFraser.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/KlageOgAnke.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/Tilbakekreving.kt

- Fjerner paragraf 18 fra klage og anke tilbakekreving
- Viser sum av netto og renter i brevtekst ikke bare netto
- Legger til sum tilbakekreving i vedlegg
- Bruker metode for klage og anke alle steder for å slippe dupliserte objekter

Fjern paragraf 18 klage anke

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/tilbakekreving/TilbakekrevingFerdig.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/tilbakekreving/TilbakekrevingFraser.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/tilbakekreving/TilbakekrevingResultat.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/tilbakekreving/TilbakekrevingVedlegg.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/Tilbakekreving.kt

Oversettelser for nynorsk og engelsk for tilbakekreving (tilbakekreving, ingen tilbakekreving og tilbakekreving ved dødsbo).

EY-3740 Oversettelser tilbakekreving

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/BarnepensjonInnvilgelse.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/BarnepensjonInnvilgelseForeldreloes.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonForeldreloesFraser.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/omstillingsstoenad/OmstillingsstoenadInnvilgelseFraser.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/innvilgelse/OmstillingsstoenadInnvilgelse.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonForeldreloes.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelse.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoenadInnvilgelse.kt

- Viser ikke utbetalingsinformasjon i innvilgelsesbrev når ytelsen er 0
- Fjerner ubrukt felt for foreldreløs-mal og døper om feltet `ingenUtbetaling` til `harUtbetaling` for å være mer konsistent med resten av malene.

EY-3748: Viser ikke utbetalingsinformasjon når utbetalingen er 0

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/BeregningAvOmstillingsstoenad.kt

Siden avkorting er et positivt tall og trekkes ifra følger restanse samme mønster. Derfor er restanse som positivt tall et trekk og restanse som et negativt tall et tillegg.

Viser tekst for restansetrekk hvis restansebeløp er positiv og motsatt

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/BarnepensjonInnvilgelseRedigerbartUfall.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonInnvilgelseFraser.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelse.kt

Gjort tilsvarende som i brev for foreldreløs her. Dette er gyldig inntil vi feks avkorter mot fengsel. Da må det på plass noe mer logikk her.

EY-3748: Hvis ikke utbetaling ved BP innvilgelse, vises tekst om avkortet mot uføretrygd

---

brevbaker-api-model-common/build.gradle.kts
build.gradle.kts
pensjon-brevbaker-api-model/build.gradle.kts
tjenestebuss-integrasjon/build.gradle.kts

Ved å bytte Maven repository for pakker fra GitHub så slipper man å logge inn i GitHub. Dette repoet er et speil av GitHub, laget og vedlikeholdt av Nav, som tilgjengeliggjør pakker fra repoer som er public

Bruk GitHub mirror så man slipper å logge inn for å hente ned pakker

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/informasjon/BarnepensjonInformasjonDoedsfallMellomAttenOgTjueVedReformtidspunkt.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonFellesFraser.kt

Ser litt rart ut ved listevisning, så prøver å erstatte `title2` med `bold`, som foreslått av brevbaker-teamet.

Bruker bold i stedet for title2 pga bug ved listevisning

---

docker-compose.yml
skribenten-backend/.nais/dev.yaml
skribenten-backend/.nais/prod.yaml
skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/model/Api.kt
skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/NavansattService.kt
skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/Norg2Service.kt
skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/services/ApiServiceTest.kt
skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/services/LegacyBrevServiceTest.kt
skribenten-web/frontend/src/types/brev.ts

`/norg2` ble fjernet når man valgte å legge på `/api/...`. Faktisk så ble den fjernet selv om man bare hadde `/lol` eller `lol`. Men ved å legge på en / på slutten av `/norg2/`, og å fjerne den fra `/api`, funker det fint. 
Jeg tror det er kanskje en spesiell regel dersom url pathen vi bruker slutter på `/api`, det er fordi vi har et endepunkt i PenService `/pen/actuator/health/readiness` og den funker helt fint 🤷

fikser kall for å hente nav enhet

---

skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/db/DatabaseSchema.kt

Lokalt hos meg feilar skribenten-testane som bruker testcontainers på at datasourcen bruker lengre tid på å starte enn det standardverdien her tillet. Aukar derfor timeout-verdien. Seks sekund er ikkje veldig mykje, men nok til at testane køyrer stabilt. Det var også det vi brukte i tilsvarande samanheng i etterlatte utan at det gjorde noko.

Aukar timeout på initielt oppsett av dataconfig før hikari feilar.

---

pdf-bygger/.nais/nais.yaml
pensjon-brevbaker/.nais/nais.yaml

Kan med det få opp relevante loggsnuttar saman med sporinga i Grafana.
Standard-verdien er elastic, så må definere den eksplisitt også no når vi overstyrer til å også sende til loki

Loggar til både ELK og til loki i Grafana

---

brevoppskrift-web/bff/src/config.ts

Omgår behovet for å deklarere opp Azure for appen
Får denne feilmeldinga etter deploy: "Error: Missing environment variable with name: AZURE_APP_CLIENT_ID
at requireEnvironment (file:///app/node_modules/@navikt/backend-for-frontend-utils/dist/config.js:7:15)"
Ser at config-klassa i biblioteket blir brukt for å tilgjengeleggjera requireEnvironment-hjelpemetoden, og i tillegg krev Azure-konfig. Vi treng ikkje å bruke denne, så kopierer heller berre over requireEnvironment-metoden direkte og omgår problematikken
Da eg gjorde endringa frå NAV til Nav endra eg nokre filer her, og da feila bygget sånn: https://github.com/navikt/pensjonsbrev/actions/runs/11559168526/job/32174561846 , og den eine podden har gått i crashloop sia da. Trur dette skal halde.

Fiksar brevoppskrift-web-deploy

---

skribenten-backend/.nais/nais.yaml
skribenten-web/bff/.nais/nais.yaml

Ser det funkar fint for brevbaker, pdf-bygger og brevmetadata, så tar det i bruk også i skribenten

Distribuert sporing også for skribenten

---

pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/TemplateResourceTest.kt

Det å lage PDF av alle etterlatte-malane treng vi ikkje eigentleg å gjera automatisk for kvar PR, det held med å lage HTML for alle.
Sparer oss _mykje_ tid under integrasjonstestkøyring.

Ikkje lag PDF av kvar etterlatte-mal for kvar einaste PR

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/aktivitetsplikt/Aktivitetsplikt.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/omstillingsstoenad/aktivitetsplikt/OmstillingsstoenadAktivitetspliktInformasjon10mndInnhold.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoendaAktivitetspliktInformasjon10mnd.kt

Fjerner også duplikat henvendelse i brevtekst

Under 100% er feil grad å mappe mot, siden den betyr i stedet != 100%

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/BarnepensjonInnvilgelseRedigerbartUfall.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonForeldreloesFraser.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonInnvilgelseFraser.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/BeregningAvBarnepensjon.kt

Legger til støtte for en ukjent avdød i barnepensjonsbrev.
Gjelder innledning i følgende brev, samt beregningsvedlegg 
- Innvilgelse barnepensjon
- Innvilgelse barnepensjon foreldreløs
- Omregning barnepensjon

EY-3360: Støtte for ukjent avdød i brev

---

docker-compose.yml
locust/locustfile.py
pdf-bygger/.nais/nais.yaml

Tester å øke requests cpu til 200m for å se om det utgjør noe forskjell. Fikser locust test etter path endringer. Gjør at locust venter på worker før den starter så man ikke må restarte tjenesten for at den skal fungere.

Tester å øke requests cpu til 200m for å se om det utgjør noe forskjell

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/ForhaandsvarselEtteroppgjoerUfoeretrygdAuto.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/OmsorgEgenAuto.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/OpphoerBarnetilleggAuto.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/UfoerOmregningEnslig.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/UngUfoerAuto.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocAlderspensjonFraFolketrygden.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocAlderspensjonFraFolketrygden2.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocFeilEtteroppgjoer2023.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocGjenlevendEtter1970.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocInformasjonHvilendeRett4Aar.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocMidlertidigOpphoerHvilenderett10Aar.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocUfoeretrygdEtterbetalingDagpenger.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocUfoeretrygdKombiDagpenger.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocUfoeretrygdKombiDagpengerInntektsavkorting.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocUfoeretrygdVarselOpphoerEktefelletillegg.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocVarselOpphoerMedHvilendeRett.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocVarselTilBrukerForsoergingstilleggIkkeTilUtbetaling.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/AdhocVarselTilBrukerMedForsoergingstilleggTilUtbetaling.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/adhoc/FeilUtsendingAvGjenlevenderett.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/legacy/redigerbar/AvslagUfoeretrygd.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/maler/example/DesignReferenceLetter.kt

Og for å få meir oversiktlege PR-ar når det kjem faktiske endringar igjen (typen må uansett endrast bort frå `Brevkode.AutoBrev` når vi går over til interfaces)

Tar bort eksplisitt typing av brevkode frå malane, for å få betre oversikt

---

pdf-bygger/latex.Dockerfile

Eksperimenterte litt lokalt og fekk feil under bygging av dockerfila på at tlmgr ikkje fantes, så fann eg etter litt leiting fila i aarch-mappa heller enn x86, og det gir jo ei slags meining i 2024.

TexLive ser ut til å ha gått over frå x86_64 til aarch64, så oppdaterer dockerfila vår ut frå det

---

.github/dependabot.yml

Gjeld vite-mode i frontend og brevbaker-api-model-common i gradle-backend, per no. Sett opp iht https://docs.github.com/en/code-security/dependabot/working-with-dependabot/guidance-for-the-configuration-of-private-registries-for-dependabot#about-configuring-private-registries-for-dependabot

Prøver å få dependabot til å takle interne avhengnadar.

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/BarnepensjonInnvilgelse.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/innvilgelse/BarnepensjonInnvilgelseForeldreloes.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/BarnepensjonOmregnetNyttRegelverkDTO.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/migrering/EnkeltVedtakOmregningNyttRegelverkFerdig.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/revurdering/BarnepensjonRevurdering.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/barnepensjon/revurdering/BarnepensjonRevurderingRedigerbartUtfall.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonFellesFraser.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/fraser/barnepensjon/BarnepensjonRevurderingFraser.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonForeldreloes.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelse.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonOmregnetNyttRegelverk.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonRevurdering.kt

Henger sammen med endringer i Gjenny
Vi har fjernet to felter i etterbretaling og endrer derfor litt på logikken i pensjonsbrev
Det er også lagt inn ny tekst ifm EY-4891
!! Denne endringen henger sammen med https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/6700

EY-4891 rydde opp i etterbetaling bp  

---

pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/Brevkode.kt
pensjon-brevbaker-api-model/src/test/kotlin/no/nav/pensjon/brev/api/model/maler/BrevkodeTest.kt

Etterlatte har per no over 50 teikn kun for redigerbart innhald i malar, som ikkje i seg sjølv blir ferdigstilt eller arkivert, så det er ikkje problematisk på kort sikt.

Rullar midlertidig tilbake 50-teikns-grense, så ting ikkje trynar i prod for etterlatte

---

pensjon-brevbaker-api-model/src/main/kotlin/no/nav/pensjon/brev/api/model/maler/Brevkode.kt
pensjon-brevbaker-api-model/src/test/kotlin/no/nav/pensjon/brev/api/model/maler/BrevkodeTest.kt

No har etterlatte fiksa sine kodar, så skrur på igjen.
Revert "Rullar midlertidig tilbake 50-teikns-grense, så ting ikkje trynar i prod for etterlatte (#1156)"
This reverts commit 72dd122098e10cfc7bbe69270aaf6736cb722717.

Skru på validering av lengde brevkode igjen

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/BrevbakerAppModule.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/FeatureToggleHandler.kt
skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/Features.kt
skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/SkribentenApp.kt

Under avslutning av pod får vi ofte feilmelding frå Unleash om Could not fetch toggles - sjå feks https://logs.adeo.no/app/r/s/2PDTD. 
_Trur_ trikset for å unngå det er å kalle Unleash sin eigen shutdown-metode.

Forbetre shutdown for Unleash

---

skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/db/EditLetterHash.kt

Å setje lengde på binær-tabellar i exposed har null effekt, og gir åtvaring (warn) i loggane, så tar det like godt bort. Under er koden frå biblioteket:
```
override fun binaryType(): String = "bytea"
override fun binaryType(length: Int): String {
exposedLogger.warn("The length of the binary column is not required.")
return binaryType()
}
```

Tar bort lengde på binær-array i exposed

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/Trygdetidstabell.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonForeldreloes.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonInnvilgelse.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonOmregnetNyttRegelverk.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/BarnepensjonRevurdering.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoenadInntektsjusteringVedtakDTO.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoenadInnvilgelse.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/etterlatte/fixtures/OmstillingsstoenadRevurdering.kt

Viser nå feks `Norge (NOR)` i stedet for bare `NOR`.

EY-4731: Vise både land på norsk og landkode i trygdetidstabell

---

.github/workflows/brevbaker-api-model.yaml
.github/workflows/pdfbygger-brevbaker.yml
.github/workflows/skribenten.yml
.github/workflows/template-model-generator.yml
.github/workflows/tjenestebuss-integrasjon.yml

Denne tar seg av caching, og er ifølgje Gradle-teamet å føretrekkje framfor feks setup-java-actionen, ref https://github.com/gradle/actions/blob/main/docs/setup-gradle.md

Bruker konsekvent setup-gradle-actionen.

---

brevbaker-dsl/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/common/KronerText.kt
brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/common/KronerText.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/VedleggMaanedligeUfoeretrgdFoerSkatt.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/VedleggOpplysningerOmEtteroppgjoeret.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/opplysningerbruktiberegningufoere/OpplysningerOmBarnetillegg.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/opplysningerbruktiberegningufoere/TabellUfoereOpplysninger.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/tilbakekreving/TilbakekrevingFraser.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/Beregningsperiodetabell.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/Beregningsperiodetabell.kt
pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/BeregningsperiodetabellEtterbetaling.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/maler/example/EksempelbrevRedigerbart.kt
pensjon-brevbaker/src/test/kotlin/no/nav/pensjon/brev/maler/example/LetterExample.kt
pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/common/Felles.kt

KronerText blir brukt frå både etterlatte og pesys, og det er eigentleg heilt greitt at vi har éin standard for korleis vi skriv ut kroner, så den tenkjer eg fint kan høyre heime i felles-kode, så flyttar inn i dsl-en.
Ei mogleg anna tilnærming er å seie at dette er opp til kvart team å ordne, og at vi dupliserer opp denne i hhv. etterlattemaler og pensjonsmaler.
Det må iallfall endrast anten den eine eller andre vegen før vi kan flytte etterlattemalane og pensjonsmalane dit dei skal.

Flytte KronerText til dsl-en

---

etterlattemaler/src/main/kotlin/no/nav/pensjon/etterlatte/maler/EtterlatteBrev.kt
etterlattemaler/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/barnepensjon/BeregningAvBarnepensjon.kt
etterlattemaler/src/main/kotlin/no/nav/pensjon/etterlatte/maler/vedlegg/omstillingsstoenad/BeregningAvOmstillingsstoenad.kt

Siden `erYrkesskade` alltid vil være en boolean ( og aldri `null`), ble aldri avsnittet om 4/5-regelen vist. Fikser på dette og endrer `erYrkesskade` til å ikke være nullable lenger (har sjekket mot brev-api).

Fikser logikk slik at manglende 4/5-dels avsnitt vises

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/routing/AutobrevRoutes.kt

Det er nok fra navnet på en call attribute fra ktor, så det kan skape konflikt om den brukes på et tidspunkt.
Jeg skulle også ønske at jeg skrev en kommentar med rasjonale for hvorfor det er kun /pdf-ruten som setter opp brevkode for call-logging.

Fiks copy-paste skriveleif

---

pensjon-brevbaker/src/main/kotlin/no/nav/pensjon/brev/BrevbakerAppModule.kt
pensjon-brevbaker/src/test/resources/application.conf

toString på ApplicationConfigValue returnerer lang string, det er getString som returnerer kun verdien.

Rettar bruk av feil metode for å hente property

---

skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/route.tsx
skribenten-web/frontend/src/routes/saksnummer_/$saksId/route.tsx

Dette er en midlertidig workaround (slik at skribenten ikke er nede i flere dager) fordi av en eller annen grunn så er `getSakContextQueryOptions` undefined i noen tilfeller når `loader` kjører. Dette kan reproduseres ved å bruke en url med query-param `enhetsId` uten hermetegn (`"`) rundt verdien, f.eks [https://pensjon-skribenten-web-q2.intern.dev.nav.no/saksnummer/22941796/brevvelger?enhetsId=4817](https://pensjon-skribenten-web-q2.intern.dev.nav.no/saksnummer/22941796/brevvelger?enhetsId=4817).

Midlertidig work-around fordi getSakContextQueryOptions er undefined

---

skribenten-backend/src/main/kotlin/no/nav/pensjon/brev/skribenten/services/KrrService.kt
skribenten-backend/src/test/kotlin/no/nav/pensjon/brev/skribenten/services/KrrServiceTest.kt

Sia det gamle skal skruast av i juni.
Obs: tilsvarande endring må også til i dokdist. Tar det etter denne er merga inn.
Testa lokalt, returnerer tilsvarande som noverande endepunkt både for person som fins i krr og person som ikkje gjer det.

Oppdaterer KRR-kall til å bruke nytt endepunkt

---

skribenten-web/frontend/src/Brevredigering/ModelEditor/components/ObjectEditor.tsx
skribenten-web/frontend/src/Brevredigering/ModelEditor/components/ScalarEditor.tsx

Som det er i main no funkar det for number-type-felt, men ikkje for f.eks. brytarar

Bruker DisplayText konsekvent for alle typar saksbehandlervalg-felt

---

.github/dependabot.yml

Ref #1455
Skriv om til å heller bruke eksplisitt liste for alt vi vil samle opp i backend-PR. Kjens tryggare og bør fungere. Gjekk gjennom toml-fila vår med avhengnadar og brukte denne for å lage lista

Dependabot-grupperinga oppførte seg ikkje som forventa

---

skribenten-web/frontend/src/Brevredigering/ModelEditor/ModelEditor.tsx
skribenten-web/frontend/src/components/brevmalAlternativer/BrevmalAlternativer.tsx
skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevvelger/-components/brevmal/BrevmalBrevbaker.tsx

Toggles for boolean-felter skal ikke vises i brevvelger, men de må allikavel sendes med som false ved opprettelse av brev.
Fikser det slik at boolean-felter registreres i brevvelger saksbehandlervalg-form med false som verdi.

Saksbehandlervalgskjema boolean-felter i brevvelger

---

etterlattemaler/build.gradle.kts
pensjon-brevbaker/build.gradle.kts
pensjonsmaler/build.gradle.kts

https://docs.gradle.org/9.0.0/userguide/upgrading_major_version_9.html#task_changes treff visst oss, sjølv om det som slår til ser ut til å vera "In previous releases, it was possible to create Test tasks without any additional configuration. By convention, Gradle used the classpath and test classes from the test source set." - og vi _har_ jo additional configuration. Men workarounden deira funka.

Oppsett for at integrasjonstestane skal køyre igjen

---

pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/fraser/vedlegg/maanedligPensjonFoerSkatt/TabellMaanedligPensjon.kt

I showIf-en nokre rader ovanfor har vi tilbakefall til 0 som standardverdi viss ektefelletillegg eller barnetillegg er null. Desse radene vil derfor visast uansett, noko som ikkje gir meining når brukar ikkje har hatt desse tillegga.
I den andre tabellen her har vi sjekk på om verdien er større enn 0, så tar tilsvarande funksjonalitet også her.

Unngår å ta med irrelevante rader.

---

skribenten-web/bff/package-lock.json
skribenten-web/bff/package.json
skribenten-web/bff/src/internalRoutes.ts

Potential fix for [https://github.com/navikt/pensjonsbrev/security/code-scanning/28](https://github.com/navikt/pensjonsbrev/security/code-scanning/28)
To fix the missing CSRF middleware, we should add a well-known CSRF protection middleware to the `/bff/internal/logg` POST route. Since the recommendation mentions using `lusca`, we'll use `lusca.csrf()` middleware. This requires:
- Importing `lusca` at the top of the file.
- Adding `lusca.csrf()` as middleware to the POST `/bff/internal/logg` handler.
- The rest of the route logic should remain unchanged.
No other routes need to be modified unless they also use cookie-based authentication for state-changing actions, but as per the provided code, only this route is affected.
_Suggested fixes powered by Copilot Autofix. Review carefully …

Potential fix for code scanning alert no. 28: Missing CSRF middleware

---

brevoppskrift-web/frontend/package-lock.json
brevoppskrift-web/frontend/package.json

Build failed with
```
error during build:
[vite:json] [plugin vite:json] vite/modulepreload-polyfill.js: Failed to parse JSON file.
file: vite/modulepreload-polyfill.js
at getRollupError (file:///Users/stw/pensjonsbrev/brevoppskrift-web/frontend/node_modules/rollup/dist/es/shared/parseAst.js:397:41)
```
Removing the override of the `vite`-dependency on `rollup/wasm-node@^4.9.2` has vite rely on a fresher version.
Build passes.

Remove vite/rollup override after update of vite

---

skribenten-web/frontend/src/routes/saksnummer_/$saksId/brevbehandler/-components/BrevbehandlerMeny.tsx

En-linje-fiks på at min-max bredde medførte at smal visning kunne gjøre at mottaker-presentasjonen i brevvelger dyttet redigeringsknappen ned på linjen under adressen der knappen ble stående helt alene og med redusert kontekst. Sånn kan vi ikke ha det 😄 Ved å fjerne wrapping på overordnet nivå vil adresselinjene foldes hvis det blir for trangt, i stedet for å folde knappen.

Fold addresse heller enn redigeringsknapp-neste-linje i brevbehandler

---

pensjonsmaler/src/main/kotlin/no/nav/pensjon/brev/maler/redigerbar/ForhaandsvarselVedTilbakekreving.kt

Tilsvarende doksysmal er konvertert og passer bedre i andre tilfeller. Den konverterte exstream varianten skal kun gjelde uføre-saker. Ref:  https://nav-it.slack.com/archives/C08H52KFD4Y/p1759833099631679?thread_ts=1759753630.046399&cid=C08H52KFD4Y

Skal skule konvertert exstream variant for alle utenom uføre.
